"""
AI Query Interface - Local test version with mocked responses
No GCP dependencies required for UI testing
"""
import os
import time
import random
from flask import Flask, render_template, request, jsonify

app = Flask(__name__)

# Configuration
PROMPT_SUFFIX = os.environ.get("PROMPT_SUFFIX", "Please provide a clear and concise response.")

# Mock responses for testing
MOCK_RESPONSES = [
    """# Response

This is a mock response for local testing. In production, this would be generated by Gemini 2.5 Pro.

## Key Points
- The interface is working correctly
- Your prompt was received and processed
- The suffix text was appended successfully

## Next Steps
1. Deploy to Cloud Run
2. Configure GCP credentials
3. Test with real Vertex AI responses""",

    """Here's a simulated AI response for your query.

**Features demonstrated:**
- Markdown rendering
- Code blocks
- Lists and formatting

```python
def example():
    return "This is a code example"
```

The full application uses Vertex AI's Gemini 2.5 Pro model for actual responses.""",

    """Thank you for your query. This mock response simulates what you'd receive from the Gemini model.

| Feature | Status |
|---------|--------|
| Prompt Input | Working |
| Suffix Append | Working |
| Response Display | Working |
| Markdown Render | Working |

Deploy to Cloud Run for production use with real AI responses."""
]


@app.route("/")
def index():
    """Render the main interface."""
    return render_template("index.html", suffix_text=PROMPT_SUFFIX)


@app.route("/query", methods=["POST"])
def query():
    """Process user prompt and return mock AI response."""
    try:
        data = request.get_json()
        user_prompt = data.get("prompt", "").strip()

        if not user_prompt:
            return jsonify({"error": "Please enter a prompt"}), 400

        # Combine user prompt with suffix
        full_prompt = f"{user_prompt}\n\n{PROMPT_SUFFIX}"

        # Simulate API delay
        time.sleep(random.uniform(0.5, 1.5))

        # Return mock response
        mock_response = random.choice(MOCK_RESPONSES)

        return jsonify({
            "response": mock_response,
            "full_prompt": full_prompt,
            "mock": True
        })

    except Exception as e:
        return jsonify({"error": str(e)}), 500


@app.route("/health")
def health():
    """Health check endpoint."""
    return jsonify({"status": "healthy", "mode": "test"})


if __name__ == "__main__":
    print("\n" + "=" * 50)
    print("  AI Query Interface - LOCAL TEST MODE")
    print("  Responses are mocked (no GCP required)")
    print("=" * 50)
    print("\n  Open: http://localhost:5000\n")

    port = int(os.environ.get("PORT", 5000))
    app.run(host="0.0.0.0", port=port, debug=True)
